MOCK_JOBS = [
    {
        "id": 1, "title": "Senior Frontend Engineer", "company": "Stripe",
        "field": "Engineering", "experience": "Senior", "location": "Remote",
        "type": "Full-time", "salary": "$160k–$200k", "salary_sort": 180000,
        "description": "Build and scale payment UI across web and mobile. Own frontend architecture for Stripe's merchant dashboard.",
        "source": "linkedin", "days_ago": 1, "featured": True,
    },
    {
        "id": 2, "title": "Product Designer", "company": "Figma",
        "field": "Design", "experience": "Mid", "location": "San Francisco",
        "type": "Full-time", "salary": "$130k–$160k", "salary_sort": 145000,
        "description": "Shape the future of collaborative design tools. Work closely with PMs and engineers on core product surfaces.",
        "source": "indeed", "days_ago": 2, "featured": False,
    },
    {
        "id": 3, "title": "ML Engineer", "company": "Cohere",
        "field": "AI/ML", "experience": "Mid", "location": "Remote",
        "type": "Full-time", "salary": "$150k–$185k", "salary_sort": 167000,
        "description": "Train and fine-tune large language models. Partner with research to bring cutting-edge NLP into production.",
        "source": "ai", "days_ago": 3, "featured": True,
    },
    {
        "id": 4, "title": "Junior Backend Developer", "company": "Razorpay",
        "field": "Engineering", "experience": "Junior", "location": "Bengaluru",
        "type": "Full-time", "salary": "₹12–18 LPA", "salary_sort": 1500000,
        "description": "Build scalable APIs and microservices powering India's largest payment infrastructure.",
        "source": "indeed", "days_ago": 1, "featured": False,
    },
    {
        "id": 5, "title": "Data Analyst", "company": "Swiggy",
        "field": "Data", "experience": "Junior", "location": "Bengaluru",
        "type": "Full-time", "salary": "₹8–12 LPA", "salary_sort": 1000000,
        "description": "Analyse delivery, demand, and growth metrics to surface insights for business and ops teams.",
        "source": "user", "days_ago": 5, "featured": False,
    },
    {
        "id": 6, "title": "UX Researcher", "company": "Google",
        "field": "Design", "experience": "Mid", "location": "Hybrid",
        "type": "Full-time", "salary": "$140k–$170k", "salary_sort": 155000,
        "description": "Run qualitative and quantitative user research to inform Google's product direction globally.",
        "source": "linkedin", "days_ago": 4, "featured": False,
    },
    {
        "id": 7, "title": "DevOps Engineer", "company": "Cloudflare",
        "field": "Engineering", "experience": "Senior", "location": "Remote",
        "type": "Full-time", "salary": "$155k–$190k", "salary_sort": 172000,
        "description": "Design and maintain CI/CD pipelines and infrastructure for one of the world's largest edge networks.",
        "source": "ai", "days_ago": 2, "featured": False,
    },
    {
        "id": 8, "title": "iOS Developer", "company": "Zomato",
        "field": "Engineering", "experience": "Mid", "location": "Bengaluru",
        "type": "Contract", "salary": "₹5k/day", "salary_sort": 1300000,
        "description": "Develop and ship features on the Zomato consumer iOS app used by millions across India.",
        "source": "user", "days_ago": 0, "featured": False,
    },
    {
        "id": 9, "title": "Growth Marketing Manager", "company": "Notion",
        "field": "Marketing", "experience": "Senior", "location": "Remote",
        "type": "Full-time", "salary": "$120k–$145k", "salary_sort": 132000,
        "description": "Own growth experiments, SEO, and lifecycle marketing to drive PLG for Notion's global user base.",
        "source": "linkedin", "days_ago": 6, "featured": False,
    },
    {
        "id": 10, "title": "AI Research Intern", "company": "DeepMind",
        "field": "AI/ML", "experience": "Junior", "location": "London",
        "type": "Internship", "salary": "£2,800/mo", "salary_sort": 2800,
        "description": "Work alongside world-class researchers on reinforcement learning and large-scale generative models.",
        "source": "ai", "days_ago": 1, "featured": True,
    },
    {
        "id": 11, "title": "Freelance Data Scientist", "company": "Zepto",
        "field": "Data", "experience": "Mid", "location": "Remote",
        "type": "Freelance", "salary": "₹80k/mo", "salary_sort": 960000,
        "description": "Build demand forecasting models and recommendation engines for a fast-growing quick commerce startup.",
        "source": "user", "days_ago": 3, "featured": False,
    },
    {
        "id": 12, "title": "Engineering Manager", "company": "Atlassian",
        "field": "Engineering", "experience": "Senior", "location": "Remote",
        "type": "Full-time", "salary": "$200k–$240k", "salary_sort": 220000,
        "description": "Lead a team of 8 engineers on Jira's core project management workflows. Drive roadmap and hiring.",
        "source": "indeed", "days_ago": 7, "featured": False,
    },
]
